AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EcsClusterName:
    Type: String
    Description: Enter ECS Cluster Name to run docker.
  EcsTaskDefinitioinArn:
    Type: String
    Description: Enter TaskDefinitionArn to run.
Resources:
  DPP4ZAOO:
    Type: 'AWS::DataPipeline::Pipeline'
    Properties:
      Name: ecs-run-task-sample
      Description: "Pipeline to run task on ECS"
      Activate: true
      PipelineObjects: 
        - 
          Id: "CliActivity"
          Name: "CliActivity"
          Fields: 
            - 
              Key: "parent"
              RefValue: "Default"
            - 
              Key: "type"
              StringValue: "ShellCommandActivity"
            - 
              Key: "runsOn"
              RefValue: "Ec2Instance"
            - 
              Key: "command"
              StringValue: "(sudo yum -y update aws-cli) && (#{myAWSCLICmd})"
        - 
          Id: "Ec2Instance"
          Name: "Ec2Instance"
          Fields: 
            - 
              Key: "parent"
              RefValue: "Default"
            - 
              Key: "type"
              StringValue: "Ec2Resource"
            - 
              Key: "instanceType"
              StringValue: "t2.micro"
            - 
              Key: "terminateAfter"
              StringValue: "10 Minutes"
        - 
          Id: "DefaultSchedule"
          Name: "Every 15 minutes"
          Fields: 
            - 
              Key: "parent"
              RefValue: "Default"
            - 
              Key: "type"
              StringValue: "Schedule"
            - 
              Key: "period"
              StringValue: "15 Minutes"
            - 
              Key: "startAt"
              StringValue: "FIRST_ACTIVATION_DATE_TIME"
        - 
          Id: "Default"
          Name: "Default"
          Fields: 
            - 
              Key: "type"
              StringValue: "Default"
            - 
              Key: "failureAndRerunMode"
              StringValue: "CASCADE"
            - 
              Key: "role"
              StringValue: "DataPipelineDefaultRole"
            - 
              Key: "schedule"
              RefValue: "DefaultSchedule"
            - 
              Key: "resourceRole"
              StringValue: "DataPipelineDefaultResourceRole"
            - 
              Key: "scheduleType"
              StringValue: "cron"
      ParameterObjects:
        - 
          Id: "myAWSCLICmd"
          Attributes: 
            - 
              Key: "description"
              StringValue: "command to execute"
            - 
              Key: "type"
              StringValue: "String"
      ParameterValues:
        - 
          Id: "myAWSCLICmd"
          StringValue:
            Fn::Join:
              - ""
              - - "AWS_DEFAULT_REGION="
                - Ref: AWS::Region
                - " aws ecs run-task --cluster "
                - Ref: EcsClusterName
                - " --task-definition "
                - Ref: EcsTaskDefinitioinArn
